# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_des',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_origin',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='watch_large_pic',
            new_name='large_pic',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='watch_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='watch_pic',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='watch_year',
            new_name='year',
        ),
    ]
