# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20170509_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
