# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-13 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20170513_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=1000)),
                ('bg', models.FileField(upload_to='')),
            ],
        ),
    ]
