# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-14 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_auto_20170514_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='bracelet_color',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='bracelet_length',
            field=models.CharField(default=43, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='bracelet_material',
            field=models.CharField(default='steel', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='case_material',
            field=models.CharField(default='steel', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='code',
            field=models.CharField(default=42142, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='movement',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('quartz', 'Quartz')], default='automatic', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='price',
            field=models.CharField(default=5000, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='ref_no',
            field=models.CharField(default=523523523, max_length=30),
            preserve_default=False,
        ),
    ]
