# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-25 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_auto_20170514_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='type',
            field=models.CharField(choices=[('all', 'All'), ('men', "Men's"), ('women', "Women's")], default='all', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
