# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0008_auto_20170602_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='color',
            field=models.CharField(default='Blue', max_length=30, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
