# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0009_watch_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.IntegerField(),
        ),
    ]
